### ISSUE TITLE
Check the object storage endpoint to determine which signature version to use

### ISSUE THREAD

**Issue by arschles** [deis/slugrunner#17]
S3 and Minio should use the S3 V4 signature version, and Google Cloud Storage in compatibility mode should use the V2 version.

Ref https://github.com/deis/builder/issues/222

**Comment by smothiki** [comment]
respective PR got merged

**Comment by arschles** [comment]
it was #19, right @smothiki ?

**Comment by smothiki** [comment]
Yes . Sorry for my lazy comment

**Comment by arschles** [comment]
No problem! Just wanted to make it a little more clear
