### ISSUE TITLE
Use deis-objectstorage-secret.yaml to get S3 credentials

### ISSUE THREAD

**Issue by smothiki** [deis/slugrunner#18]
[Object storage docs](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#credentials) should also be upgraded when this work is done.

Related: deis/workflow#61

**Comment by arschles** [comment]
@smothiki @helgi can we move this to RC? It doesn't seem necessary to get this in for beta, given that we've decided to keep builder on the 'minio-user' secret

**Comment by arschles** [comment]
also, is this a dependency of https://github.com/deis/workflow/issues/458?

**Comment by bacongobbler** [comment]
removing from beta milestone

**Comment by arschles** [comment]
[Object storage docs](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#credentials) should also be upgraded when this work is done.

**Comment by arschles** [comment]
Related work: https://github.com/deis/slugbuilder/issues/32 and https://github.com/deis/builder/issues/224

**Comment by kmala** [comment]
fixed in #24
