### ISSUE TITLE
Remove the hardcoded entrypoint

### ISSUE THREAD

**Issue by arschles** [deis/slugrunner#23]
There is a comment in the [deis/controller](https://github.com/deis/controller)'s `rootfs/api/models/app.py` file that reads: `FIXME: remove slugrunner's hardcoded entrypoint`

**Comment by arschles** [comment]
See https://github.com/deis/controller/pull/497#discussion_r56419536 for discussion that prompted opening this issue.

**Comment by bacongobbler** [comment]
I don't think this will ever be able to happen due to backwards compatibility issues, so I'm going to close this. 🙍
