### ISSUE TITLE
Change version to 2.0.0-dev

### ISSUE THREAD

**Issue by mboersma** [deis/slugrunner#3]
slugrunner still has this in its Dockerfile: `ENV DEIS_RELEASE 1.11.0-dev`. Should be updated before v2 beta.

(Is `ENV DEIS_RELEASE` necessary now? It was originally to force Deis containers from different releases to be distinct, because `docker images` could otherwise display one of many tags for a given image. We wanted `docker ps` to display consistent `:v1.10.2` tags for all Deis containers. I think `docker` itself may have fixed this behavior now.)

**Comment by bacongobbler** [comment]
> Is ENV DEIS_RELEASE necessary now?

Only one way to test :)

**Comment by technosophos** [comment]
That's the status on this, and is it definitely a beta1 issue?
