### ISSUE TITLE
Bug: exec: bash -c: not found

### ISSUE THREAD

**Issue by krancour** [deis/slugrunner#31]
Seen on recent deploy of buildpack apps:

```
$ kubectl logs iambic-offering-v2-web-s63x6 --namespace=iambic-offering --previous
2016/04/19 17:43:23 Successfully copied home/iambic-offering:git-5450cbcd/push/slug.tgz to slug.tgz
/runner/init: line 76: exec: bash -c: not found
```

Seems traceable back to here:

https://github.com/deis/slugrunner/pull/27/files

I have a PR already in the works to correct this without completely reverting https://github.com/deis/slugrunner/pull/27/files

cc @mboersma

**Comment by bacongobbler** [comment]
fwiw I'm on workflow-dev deploying example-go without issue
