### ISSUE TITLE
Pull in patches for security vulnerabilities

### ISSUE THREAD

**Issue by sgoings** [deis/slugrunner#47]
The 2.0.0 release of slugrunner has a _few_ unpatched security vulnerabilities (medium + lower):

https://quay.io/repository/deis/slugrunner/image/d89fe58c8bc2356f494c7e5b0a9540cf10b588dea206413a68c8dcc220ffe04d?tab=vulnerabilities

We should pull in updated packages where appropriate.

**Comment by arschles** [comment]
moving out of 2.2, to be addressed in the near future

**Comment by Joshua-Anderson** [comment]
Heroku hasn't pushed a new cedar stack to github in 2 months. Is there anything that can be done besides maintaining our own fork of the cedar stack that is more up to date?
