### ISSUE TITLE
Git vulnerability

### ISSUE THREAD

**Issue by Bregor** [deis/slugrunner#67]
[USN-3387-1](http://www.security-database.com/detail.php?alert=USN-3387-1)
Slugrunner is affected:

    $ kubectl exec -n appname appname-web-2095715944-ckzh5 -- dpkg -l|grep -w git|head -1|grep -Eo '1:[^ ]+'
    1:1.9.1-1ubuntu0.3

**Comment by mboersma** [comment]
Probably means we need to rev the base image to get upstream Ubuntu fixes, then rebuild everything off that. A bit of a chore, but we have some scripting to help.

**Comment by mboersma** [comment]
With the most recent `quay.io/deis/slugrunner:v2.4.0` it's been updated:
```shell
$ docker run -it --entrypoint bash quay.io/deis/slugrunner:v2.4.0 
slug@c26b20b637cd:~$ dpkg -l|grep -w git|head -1|grep -Eo '1:[^ ]+'
1:1.9.1-1ubuntu0.5
```
The [security scan](https://quay.io/repository/deis/slugrunner/image/30cd3e167d7f3fa675bac1aa277bb6fbdb94ffe826bf6065371f6e041e814f44?tab=vulnerabilities) shows only medium vulnerabilities. @Bregor is there still a patch needed here?
